---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: s3-upload-proxy

steps:
  - name: mod-download
    image: &goimage "golang:1.12.4"
    commands:
      - go mod download
    environment:
      GOPROXY: https://proxy.golang.org

  - name: test
    image: *goimage
    commands:
      - go test -race ./...
    depends_on:
      - mod-download

  - name: lint
    image: golangci/golangci-lint
    pull: always
    commands:
      - golangci-lint run --enable-all -D lll -D errcheck ./...
    depends_on:
      - mod-download

  - name: build
    image: *goimage
    commands:
      - go build -o s3-upload-proxy
    environment:
      CGO_ENABLED: 0
    depends_on:
      - mod-download

  - name: build-and-push-to-dockerhub
    image: plugins/docker
    settings:
      repo: fsouza/s3-upload-proxy
      auto_tag: true
      dockerfile: ci/Dockerfile
      username:
        from_secret: docker_user
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/tags/*
        - refs/heads/master
    depends_on:
      - test
      - lint
      - build
---
kind: signature
hmac: 059453453db602404058daba3cf53719bb2903bb4339ec2381f0e9a5bf59dbbf

...
