---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: golang:1.11
    commands:
      - go test -race ./...

  - name: push-to-dockerhub
    image: plugins/docker
    settings:
      repo: fsouza/s3-upload-proxy
      auto_tag: true
      username:
        from_secret: docker_user
      password:
        from_secret: docker_password
    when:
      ref:
        - refs/tags/*
        - refs/heads/master
