version: "3.7"

services:
  s3-upload-proxy:
    build: .

    environment:
      BUCKET_NAME: local-bucket
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: S3RVER
      AWS_SECRET_ACCESS_KEY: S3RVER
      S3_ENDPOINT: http://172.17.0.1:8000
      HTTP_PORT: 5000

    ports:
      - 5000:5000
